# Generated by Django 5.1.5 on 2025-02-05 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clmsapp', '0002_otpverification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='photo',
        ),
    ]
