# Generated by Django 5.1.5 on 2025-02-05 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clmsapp', '0003_remove_user_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpverification',
            name='expires_at',
        ),
    ]
