# Generated by Django 5.1.6 on 2025-03-27 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clmsapp', '0004_leaveapplication_forwarded_to_dean_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='incharge',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'Incharge'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leaves', to=settings.AUTH_USER_MODEL),
        ),
    ]
