# Generated by Django 5.1.6 on 2025-03-28 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clmsapp', '0006_remove_leaveapplication_forwarded_to_dean_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaveapplication',
            name='status',
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='forwarded_to_dean',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='incharge_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='leave_files/'),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='incharge',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'Incharge'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leaves', to=settings.AUTH_USER_MODEL),
        ),
    ]
