# Generated by Django 5.1.6 on 2025-03-31 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clmsapp', '0007_remove_leaveapplication_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved by Incharge', 'Approved by Incharge'), ('Rejected by Incharge', 'Rejected by Incharge'), ('Forwarded to Dean', 'Forwarded to Dean')], default='Pending', max_length=30),
        ),
    ]
