# Generated by Django 5.1.6 on 2025-03-31 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clmsapp', '0008_leaveapplication_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='leave_attachments/'),
        ),
    ]
